### ISSUE TITLE
Add Repo Link

### ISSUE THREAD

**Issue by dbetm** [Wolfteinter/Pic2Hubble#20]
Add link to the Git repo on GitHub on the front-end in order to invite to contribute

**Comment by samyosm** [comment]
Hey, I think I can do that.

I'm going to add a contribute floating button on the bottom left of the screen.

**Comment by samyosm** [comment]
![image](https://user-images.githubusercontent.com/99157490/174636791-f4208d27-3ae2-4630-9ae8-241154ec2866.png)

That's what I've done

**Comment by dbetm** [comment]
Great contribution @osmium-dev 

thanks 🎉
